### ISSUE TITLE
question on mesos hostname

### ISSUE THREAD

**Issue by astewart-twist** [dontrebootme/compose-mesos#2]
What's the reason for hard coding the MESOS_HOSTNAME env for containers that are linked to the mesos1 container?  Shouldn't it just be MESOS_HOSTNAME:mesos1 ?

```
slave1:
  image: redjack/mesos-slave:0.21.0
  ports:
    - "5051:5051"
  links:
    - "zk1:zookeeper1"
    - "mesos1"
  environment:
    MESOS_MASTER: zk://zookeeper1:2181/mesos
    MESOS_ISOLATOR: "cgroups/cpu,cgroups/mem"
    MESOS_CONTAINERIZERS: "docker,mesos"
    MESOS_EXECUTOR_REGISTRATION_TIMEOUT: "5mins"
    MESOS_HOSTNAME: 192.168.59.103
    MESOS_PORT: "5051"
    MESOS_LOG_DIR: /var/log
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/local/bin/docker
    - /sys/fs/cgroup:/sys/fs/cgroup
```
